### PR TITLE
Added namedtuples data structure

### PR DESCRIPTION
**Pull request by HKABIG**
*Please read the [contributing guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md) before submitting a pull request.*

---

**Describe the change**
Added namedtples.py file in ultimatepython datastructures folder featuring a step by step explanation of the namedtuple datastructure.

**Additional context**
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by huangsam** [comment]
Can we add this module to all README files?

**Comment by HKABIG** [comment]
> Can we add this module to all README files?

Yes I will do that

**Comment by HKABIG** [comment]
@huangsam I have successfully committed changes to the branch

**Review by huangsam — CHANGES_REQUESTED** [review]
Please create a main function for your code and use assert statements instead of print statements. See previous lessons as an example

**Comment by HKABIG** [comment]
@huangsam please review I have added assertions and main function

**Review by huangsam — APPROVED** [review]

**Comment by huangsam** [comment]
Thanks for the lesson!

**Pull request merged**
