### PR TITLE
Added project-based-learning repo link to README.md

### LINKED ISSUE #80: Adding project-based-learning repo to additional resources
I came across this github repository which has a bunch of python projects. The repo is called project-based-learning and is very popular. It has projects in several programming languages. I would like to suggest that we should add this repo link to the github repositories provided under additional resources. I can create a fork, add it and then create a PR. Can I have permission to do this?

### PR DESCRIPTION
**Pull request by Azeen3003**
*Please read the [contributing guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md) before submitting a pull request.*

---
closes #80 

Description: Added link to project-based-learning repository (which has over 117k stars) in GitHub repos under additional resources. It has a list of python projects which can help people learn python through a more practical project-based way.

### CODE REVIEW

**Comment by huangsam** [comment]
Thanks @Azeen3003 for adding the link. Can you add it to the other README files as well?

**Comment by Azeen3003** [comment]
> Thanks @Azeen3003 for adding the link. Can you add it to the other README files as well?

Yeah sure, I'll add them right away!

**Comment by Azeen3003** [comment]
Done @huangsam

**Comment by huangsam** [comment]
Good job. Thanks a lot for the PR!

**Comment by Azeen3003** [comment]
You're welcome. This was one of my first contributions to open-source.

**Pull request merged**
