### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harshhere905**
**Describe the change**
Added GeeksForGeeks and Coderbyte links to help the users to learn programming.
Also added a freecodecamp github repository which is very usefull.

### CODE REVIEW

**Comment by harshhere905** [comment]
@huangsam sorry for the other PR but the platforms I added are good for experienced as well as beginner programmers.
also the freecodecamp repo will help

**Comment by huangsam** [comment]
Can you please add to the other README files as well?

**Comment by harshhere905** [comment]
@huangsam i have added in all repo's and raised the pr's. You can now merge them

**Comment by huangsam** [comment]
@harshhere905 done. Thanks again for the PRs

**Pull request merged**
