### PR TITLE
Added tutorial for Linked List and reformatted it to match styling

### PR DESCRIPTION
**Pull request by The-APK**
*Please read the [contributing guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md) before submitting a pull request.*

---

**Describe the change**

- Added a new tutorial python file for Linked List data structure, demonstrating the creation, deletion and display of linked list.
- I made the code clear, concise and easy to understand for users.  
- This is for hacktoberfest, but as a developer, I thrive to contribute more towards open source.
- 
**Additional context**
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by huangsam** [comment]
While this is a useful lesson for CS students, I'm wondering if this lesson is duplicative w.r.t. the `deque.py` lesson which already talks about linked lists, but at a higher level

**Comment by huangsam** [comment]
Also the build is failing so please fix that ASAP before I proceed with reviewing this change any further

**Comment by The-APK** [comment]
Done with the fixing the build fail errors @huangsam. Thanks for the support.

**Comment by huangsam** [comment]
Can you also make sure that all the PR checks pass as well?

**Comment by The-APK** [comment]
> Can you also make sure that all the PR checks pass as well?

The same errors are throwing up even after locally testing the codes, dont know why :((

**Comment by The-APK** [comment]
@huangsam will this code coverage error matter? All the required build tests are passed.

**Comment by huangsam** [comment]
Yes it does matter. Please ensure that the code coverage for your module is high

**Pull request closed without merging**
