### PR TITLE
Fixed Emoji Visibility

### PR DESCRIPTION
**Pull request by AnimishY**
*Please read the [contributing guidelines](https://github.com/huangsam/ultimate-python/blob/master/CONTRIBUTING.md) before submitting a pull request.*

---

**Describe the change**
Enhanced visibility of Emoji as earlier it used to appear as the name for the emoji, now it shows the emoji itself

**Additional context**
image

### CODE REVIEW

**Review by huangsam — COMMENTED** [review]
Can you please add this change to the other README files as well? Thanks!

**Comment by AnimishY** [comment]
Will do, but I am not really familiar with this pull request and merge and all, so I might end up creating multiple pull requests. Just merge all those.

**Comment by AnimishY** [comment]
All READMEs updated (5 in total).

**Comment by huangsam** [comment]
Thanks!

**Review by huangsam — APPROVED** [review]

**Comment by AnimishY** [comment]
@huangsam Was my first time doing some sort of contribution here on GitHub.

**Comment by huangsam** [comment]
@AnimishY congrats on your first contribution 👌

**Pull request merged**
